### PR TITLE
Add a test of multi-in with single-in decoration

### PR DESCRIPTION
**Pull request by hham**
This PR add a test of AutoFilter with multi-in and single-in to show that a filter with multi-in and single-in is not allowed for now.

### CODE REVIEW

**Comment by codemercenary** [comment]
Thank you, @hham !  This is awesome.

**Comment by hham** [comment]
Sure.

**Comment by jdonald** [comment]
So this is still broken on clang, but somehow works with gcc?

If I instantiate <tt>\[\&f_called](float\& out) { out = ++f_called; }</tt> before the multi-decoration, somehow the test passes.

**Comment by codemercenary** [comment]
That is very strange indeed, a good finding too--should help me track this one down once I get some time to work on it.

**Comment by codemercenary** [comment]
@jdonald would you mind merging this one?

**Comment by hham** [comment]
Works fine on Unit tests on my Mac.

**Comment by jdonald** [comment]
I double-checked that the test as originally written by Hyoung (floating-point variable and all), now passes on clang.

**Pull request merged**
