### PR TITLE
autowiring::parallel

### PR DESCRIPTION
**Pull request by gtremper**
Adds a basic version of fan-out and gathering utility.

- [x] Platform team has said its farewells
- [x] Tracking team has said its farewells
- [x] Front-end team has said its farewells
- [x] QA team has said its farewells

### CODE REVIEW

**Comment by codemercenary** [comment]
Good work, @gtremper .  We will miss your contributions.

Leap on.

**Comment by kmertens** [comment]
Wishing you the best @gtremper! Good luck :)

**Comment by git-shaun** [comment]
@gtremper It was a blast, good luck to you!

**Comment by RecursiveCptHook** [comment]
@gtremper sad to hear of your departure. Nevertheless, thanks for all of your amazing contributions to Leap! You and your work will be missed. Best of luck to you in your future endeavors! Keep on keeping on and leap on! :smile:

**Comment by gtremper** [comment]
Thanks everyone!

**Comment by pehrlich** [comment]
:shipit:

**Comment by wal-rus** [comment]
@gtremper Will miss having you around!  Thanks for the awesome work!

**Comment by hham** [comment]
@gtremper Thank you for all your help about autowiring. I appreciate it. Hope I can have another chance to work with you again someday. Good luck with your new journey.

**Comment by gittyupagain** [comment]
@gtremper, it has been great working with you. I'm gonna miss seeing you so often. Hopefully we meet again.

**Comment by jdonald** [comment]
Peace!

**Comment by Okyara** [comment]
Hey Graham, it was great working with you. I will miss your awesomeness around here. Keep it up with those spectacular t-shirts.

**Comment by jo3w4rd** [comment]
I'm sorry to hear that you are leaving, but trust that you have exciting new adventures ahead of you!

**Comment by vdods** [comment]
Godspeed, fair wizard.

AutoGoodbye.

**Comment by RandomOutput** [comment]
@gtremper Sad you're headed out, good luck on your new path. :ship:

**Comment by protodeep** [comment]
Graham, sad to hear you're splitting!  Hope the next phase rocks for you!

**Comment by rabedik** [comment]
Best of luck, we'll miss you around here. Thank you for all of your contributions (esp. this one, it looks ripe and juicy) and I'm positive you'll keep kicking ass in whatever you do.

**Comment by codemercenary** [comment]
`CoreContext::SignalShutdown(true, ShutdownMode::Graceful)`

**Comment by jhe-** [comment]
I've been blessed to work with you @gtremper, You have taught me many things, and the team will sorely miss your positive spirit.

Stay strong, and Leap on.

**Comment by andrewlittlefield** [comment]
Best of luck moving forward! 

Cheers, 

Andrew

**Comment by leapmotion-services** [comment]
Great working with you Graham. Wishing you good fortune on your next
adventure.

On Friday, June 26, 2015, Graham Tremper <notifications@github.com> wrote:

> Adds a basic version of fan-out and gathering utility.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/leapmotion/autowiring/pull/620
> Commit Summary
>
>    - Create files for autowiring::parallel feature
>    - Basic outline of autowiring::parallel
>    - Basic working version of autowiring::parallel
>    - Fix synchronization bug in autowiring::parallel
>
> File Changes
>
>    - *A* autowiring/Parallel.h
>    <https://github.com/leapmotion/autowiring/pull/620/files#diff-0> (120)
>    - *M* src/autowiring/CMakeLists.txt
>    <https://github.com/leapmotion/autowiring/pull/620/files#diff-1> (2)
>    - *A* src/autowiring/Parallel.cpp
>    <https://github.com/leapmotion/autowiring/pull/620/files#diff-2> (4)
>    - *M* src/autowiring/test/CMakeLists.txt
>    <https://github.com/leapmotion/autowiring/pull/620/files#diff-3> (1)
>    - *A* src/autowiring/test/ParallelTest.cpp
>    <https://github.com/leapmotion/autowiring/pull/620/files#diff-4> (39)
>
> Patch Links:
>
>    - https://github.com/leapmotion/autowiring/pull/620.patch
>    - https://github.com/leapmotion/autowiring/pull/620.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leapmotion/autowiring/pull/620>.
>

-- 
NOTE: The information in this message and any attachments is confidential 
information intended only for the individual to whom it is addressed.  If 
you are not the intended recipient, any distribution of this message or its 
attachments is prohibited.  If you have received this email in error, 
please immediately notify us and delete the message.  Thank you.

**Comment by jschunick-leap** [comment]
Hey dude - hope you enjoy your next adventure, it was a pleasure working with you at LEAP

**Comment by clkruse** [comment]
Great sitting across from you for the past few months, Graham. Enjoyed having a fellow satellite imagery observer across the way. Best of luck!
screen shot 2015-06-26 at 5 56 16 pm

**Comment by Kip27** [comment]
<sadgoodbye>
Best of luck out there in the real world Graham!
</sadgoodbye>

**Comment by neeeloy** [comment]
gonna miss having you around the office. good luck with everything and see you around the city!

**Comment by leapmotion-services** [comment]
Keep on leaping, Graham!



—
Sent from Mailbox

On Fri, Jun 26, 2015 at 6:10 PM, neeeloy <notifications@github.com> wrote:

> gonna miss having you around the office. good luck with everything and see you around the city!
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/leapmotion/autowiring/pull/620#issuecomment-115930843
-- 
NOTE: The information in this message and any attachments is confidential 
information intended only for the individual to whom it is addressed.  If 
you are not the intended recipient, any distribution of this message or its 
attachments is prohibited.  If you have received this email in error, 
please immediately notify us and delete the message.  Thank you.

**Comment by Anvil102** [comment]
It was a pleasure working with you Graham! Thanks for the great finishing piece! All the best to you on your next adventure.

**Comment by gtremper** [comment]
Thanks everyone for your comments. It means a lot to me.

**Comment by codemercenary** [comment]
I think this pull request has more participation than any other PR in Autowiring history.

**Comment by c-zheng** [comment]
And good luck! -- from someone who is truly impressed by AutoWiring :+1:

**Comment by jnguyen75** [comment]
Good luck to you and your future endeavors!  You have a bright future ahead of you.

**Comment by testmasterbright** [comment]
Good luck man!  We'll miss you!

**Comment by codemercenary** [comment]
That's a wrap.  Let's get this merged.

**Pull request merged**
