### PR TITLE
arm: remove autoboost headers

### PR DESCRIPTION
**Pull request by Okyara**
- [ ] Verify this still builds on Android

### CODE REVIEW

**Comment by jdonald** [comment]
This builds for aarch64 gcc 4.9, but not the 32-bit arm gcc 4.8, as we require boost::future.

If you want to take a step toward our gcc 4.9 r10d NDK upgrade, you could make this code conditional on the gcc version.

**Comment by jdonald** [comment]
Talked to Oksana about this in person and now understand the purpose behind it. These were her local changes to build for ARM Linux.

What we really need to do is a simpler change: replace the autowiring_build_ARM condition with something like autowiring_build_ANDROID. That is, continue using autoboost for Android, but not use it for ARM Linux or anything else. Oksana will fix this soon.

**Comment by jdonald** [comment]
Oh, we also need the corresponding changes to <tt>#cmakedefine01 autowiring_BUILD_ANDROID</tt> AutowiringConfig.h.in, and set the new CMake variable around line 15 of CMakeLists.txt

So this merge likely broke Android 32-bit.

**Comment by codemercenary** [comment]
This pull request was incorrectly targeted at master.  I have done the merge again and pushed it to develop instead in commit ddf684a90

**Pull request merged**
